version: '3.7'
services:
  app:
    build:
      context: "./"
      target: "base"
    env_file:
      - .env
    command: [ "bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0" ]
    volumes:
      - ".:/app"
      - "bundle:/usr/local/bundle"
    environment:
      RAILS_ENV: development
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: jirolifelog
      DATABASE_HOST: db
    depends_on:
      - db
    ports:
      - "3000:3000"
  frontend:
    build:
      context: "./"
      target: "base"
    env_file:
      - .env
    command: [ "npm", "start" ]
    volumes:
      - ".:/app"
    environment:
      NODE_ENV: development
    depends_on:
      - app
    ports:
      - "4000:4000"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: jirolifelog
    volumes:
      - "db-data:/var/lib/mysql"
    ports:
      - '3316:3306'

volumes:
  db-data:
    driver: local
  bundle:
    driver: local
